// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

console.log("Loading Stimulus controllers...")

import SciformationImportController from "./sciformation_import_controller"
application.register("sciformation-import", SciformationImportController)
console.log("Registered sciformation-import controller")

import SmilesController from "./smiles_controller"
application.register("smiles", SmilesController)
console.log("Registered smiles controller")
