// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application"

console.log("Loading Stimulus controllers...")

import SciformationImportController from "controllers/sciformation_import_controller"
application.register("sciformation-import", SciformationImportController)
console.log("Registered sciformation-import controller")

import SmilesController from "controllers/smiles_controller"
application.register("smiles", SmilesController)
console.log("Registered smiles controller")

import ChemicalSearchController from "controllers/chemical_search_controller"
application.register("chemical-search", ChemicalSearchController)
console.log("Registered chemical-search controller")