default: &default
  dispatchers:
    - polling_interval: <%= ENV.fetch("SOLID_QUEUE_POLLING_INTERVAL", 1) %>
      batch_size: 500
  workers:
    - queues: "*"
      threads: 3
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: <%= ENV.fetch("SOLID_QUEUE_POLLING_INTERVAL", 0.1) %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  dispatchers:
    - polling_interval: <%= ENV.fetch("SOLID_QUEUE_POLLING_INTERVAL", 2) %>
      batch_size: 100
  workers:
    - queues: "*"
      threads: <%= ENV.fetch("SOLID_QUEUE_THREADS", 2) %>
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: <%= ENV.fetch("SOLID_QUEUE_POLLING_INTERVAL", 1) %>
